// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAV5w0UuCbPhMqRmlPpiR5oAi1qmNs0Kw',
    appId: '1:622231074421:web:87bb068ad2ca0f607cea3c',
    messagingSenderId: '622231074421',
    projectId: 'lf-objects',
    authDomain: 'lf-objects.firebaseapp.com',
    storageBucket: 'lf-objects.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-bnV9iYWOETcZ-ipiLBorZ6f_bbooH4E',
    appId: '1:622231074421:android:3d5aec408e2e0b257cea3c',
    messagingSenderId: '622231074421',
    projectId: 'lf-objects',
    storageBucket: 'lf-objects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQTj0yX8T9EWzjl0-145OQhAy_fEQ7qvA',
    appId: '1:622231074421:ios:3c1eb0f589a9884e7cea3c',
    messagingSenderId: '622231074421',
    projectId: 'lf-objects',
    storageBucket: 'lf-objects.appspot.com',
    iosBundleId: 'com.example.objectsFoundLost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQTj0yX8T9EWzjl0-145OQhAy_fEQ7qvA',
    appId: '1:622231074421:ios:3c1eb0f589a9884e7cea3c',
    messagingSenderId: '622231074421',
    projectId: 'lf-objects',
    storageBucket: 'lf-objects.appspot.com',
    iosBundleId: 'com.example.objectsFoundLost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAV5w0UuCbPhMqRmlPpiR5oAi1qmNs0Kw',
    appId: '1:622231074421:web:ebe824b1202066b77cea3c',
    messagingSenderId: '622231074421',
    projectId: 'lf-objects',
    authDomain: 'lf-objects.firebaseapp.com',
    storageBucket: 'lf-objects.appspot.com',
  );
}
